config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  #get 'admin/index'
  #get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  #get 'store/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :products do
  #  get :who_bought, on: :member
  #end

  resources :contacts
  resources :products

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root to: 'store#index', as: 'store', via: :all
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :title, uniqueness: true, length: { minimum: 10 }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "URL must point to a jpg, png or gif image!"
  }

  # вывод товара, который подвергался изменениям последним.
  def self.latest
    Product.order(:updated_at).last
  end

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Commodity items exist')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  before_action :product, only: %i[show edit update]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.valid?
      @product.save
      redirect_to products_path
    else
      render action: 'new'
    end
  end

  def index
    @products = Product.all
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render action: 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_path
  end

  private

  def product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:id, :title, :description, :image_url, :price)
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end

    end
  end
end

app/views/products/edit.html.erb
<%= form_for :product, url: product_path(@product), method: :put do |p| %>
  <% if @product %>
    <% @product.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <div class='field'>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </div>
  <div class='field'>
    <%= p.label :description %><br>
    <%= p.text_area :description, rows: 6 %>
  </div>
  <div class='field'>
    <%= p.label :image_url %><br>
    <%= p.text_field :image_url %>
  </div>
  <div class='field'>
    <%= p.label :price %><br>
    <%= p.text_area :price %>
  </div>
  <div class='action'>
    <%= p.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>
<h3>Title Description Image url Price</h3>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

      <td>
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>

      <td class='list_description'>
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
            length: 80) %></dd>
        </dl>
      </td>

      <td class='list_actions'>
        <%= link_to 'Show', product_path(product) %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/>
        <%= link_to 'Destroy', product_path(product), method: :delete,
                    data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for :product, url: products_path do |p| %>
  <% if @product.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@product.errors.count, 'error') %>
      prohibited this product from being saved: </h2>

      <ul>
        <%= @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </div>
  <div class='field'>
    <%= p.label :description %><br>
    <%= p.text_area :description, rows: 6 %>
  </div>
  <div class='field'>
    <%= p.label :image_url %><br>
    <%= p.text_field :image_url %>
  </div>
  <div class='field'>
    <%= p.label :price %><br>
    <%= p.text_area :price %>
  </div>
  <div class='action'>
    <%= p.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Show product</h1>

<p><%= @product.title %><p>
  <p><%= @product.price %>$</p>